### ISSUE TITLE
Windows warns about running scaffolding.exe

### ISSUE THREAD

**Issue by HenningKlokkeraasen** [Creuna-Oslo/Episerver.Basis.Slim#12]
Environment:
Windows 10

Steps to reproduce:
Download latest scaffolding.exe
Double-click scaffolding.exe

Result:
> Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

You have to click "More info" and "Run away" to run the exe.

**Comment by Arthyon** [comment]
This is partly impossible to fix. Windows Defender uses multiple sources to determine if an app is unrecognized, including if it is signed (possible to fix) and global usage statistics (which will be hard).

I will close this with the wontfix-label as a signed executable will only get us so far.
