### ISSUE TITLE
The batch file cannot be found

### ISSUE THREAD

**Issue by Sriess** [Creuna-Oslo/Episerver.Basis.Slim#2]
When the build.cmd completes it outputs the line "The batch file cannot be found".

![bilde](https://cloud.githubusercontent.com/assets/4612472/24391944/fffe131a-1391-11e7-8f3f-cd13f9d60d2b.png)

**Comment by Arthyon** [comment]
This is an artifact of the clean up process, as the script deletes itself. 

This can be fixed by spawning a subroutine that deletes the file after script execution is finished like so:
```
call :deleteSelf&exit /b
:deleteSelf
start /b "" cmd /c del "%~f0"&exit /b
```

Purely a cosmetic change, but I'll consider it.

**Comment by Arthyon** [comment]
The scripts will be removed in newer releases, so this will not be fixed.
